# Generated by Django 5.1.5 on 2025-05-14 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0006_gameprogress_consecutive_low_performance'),
        ('children', '0005_session_active_session_daily_progress_and_more'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('day', 'Daily'), ('week', 'Weekly'), ('month', 'Monthly')], max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_sessions', models.IntegerField(default=0)),
                ('correct_answers', models.IntegerField(default=0)),
                ('incorrect_answers', models.IntegerField(default=0)),
                ('average_score', models.FloatField(default=0)),
                ('total_time_spent', models.IntegerField(default=0)),
                ('average_time_per_session', models.FloatField(default=0)),
                ('score_change', models.FloatField(default=0)),
                ('time_change', models.FloatField(default=0)),
                ('strengths', models.JSONField(default=list)),
                ('weaknesses', models.JSONField(default=list)),
                ('improvements', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_analysis', to='children.child')),
                ('game_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.gametype')),
            ],
            options={
                'unique_together': {('child', 'game_type', 'period', 'start_date', 'end_date')},
            },
        ),
    ]
