# Generated by Django 5.1.5 on 2025-02-01 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('SPEECH', 'Speech'), ('BEHAVIOR', 'Behavior')], max_length=10)),
                ('difficulty_level', models.IntegerField()),
                ('duration', models.IntegerField()),
            ],
        ),
    ]
