# Generated by Django 5.1.5 on 2025-05-03 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('age_group', models.CharField(choices=[('3-5', '3-5 years'), ('6-8', '6-8 years'), ('9-12', '9-12 years')], max_length=10)),
                ('difficulty', models.IntegerField(choices=[(1, 'Easy'), (2, 'Medium'), (3, 'Hard')])),
                ('character1_name', models.CharField(default='Character 1', max_length=100)),
                ('character2_name', models.CharField(default='Character 2', max_length=100)),
                ('dialogues', models.JSONField(default=list)),
                ('option1', models.CharField(max_length=255)),
                ('option2', models.CharField(max_length=255)),
                ('option3', models.CharField(max_length=255)),
                ('option4', models.CharField(blank=True, max_length=255, null=True)),
                ('correct_option', models.IntegerField()),
                ('correct_feedback', models.CharField(default='Great job! That was the right choice.', max_length=255)),
                ('incorrect_feedback', models.CharField(default="Let's try again. Think about how the other person might feel.", max_length=255)),
            ],
        ),
    ]
