# Generated by Django 5.1.5 on 2025-05-03 22:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_socialscenario'),
        ('children', '0003_alter_child_age_alter_child_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('max_difficulty', models.IntegerField(default=3)),
                ('progression_threshold', models.IntegerField(default=10)),
                ('code', models.CharField(choices=[('FACIAL', 'Facial Expressions'), ('MATCHSORT', 'Match and Sort'), ('SOCIAL', 'Social Scenarios')], max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty_level', models.IntegerField()),
                ('correct_answers', models.IntegerField(default=0)),
                ('incorrect_answers', models.IntegerField(default=0)),
                ('total_questions', models.IntegerField(default=0)),
                ('score_percentage', models.FloatField(default=0)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('session_data', models.JSONField(blank=True, default=dict)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_sessions', to='children.child')),
                ('game_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.gametype')),
            ],
        ),
        migrations.CreateModel(
            name='GameProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_difficulty', models.IntegerField(default=1)),
                ('correct_answers', models.IntegerField(default=0)),
                ('incorrect_answers', models.IntegerField(default=0)),
                ('total_games_played', models.IntegerField(default=0)),
                ('score_percentage', models.FloatField(default=0)),
                ('last_played', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_progress', to='children.child')),
                ('game_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.gametype')),
            ],
            options={
                'unique_together': {('child', 'game_type')},
            },
        ),
    ]
