# Generated by Django 5.1.5 on 2025-05-04 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_gametype_gamesession_gameprogress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamesession',
            name='duration_seconds',
        ),
        migrations.RemoveField(
            model_name='gamesession',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='gamesession',
            name='start_time',
        ),
    ]
