# Generated by Django 5.1.5 on 2025-05-04 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_remove_gamesession_duration_seconds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
