# Generated by Django 5.1.5 on 2025-05-04 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_gamesession_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameprogress',
            name='consecutive_low_performance',
            field=models.IntegerField(default=0),
        ),
    ]
