# Generated by Django 5.1.5 on 2025-02-19 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='age',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='child',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='child',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female'), ('other', 'other')], max_length=6),
        ),
        migrations.AlterField(
            model_name='child',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='child',
            name='time_of_practice',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
