# Generated by Django 5.1.5 on 2025-05-04 14:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0003_alter_child_age_alter_child_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='session',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='session',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='session',
            name='start_time',
        ),
        migrations.AddField(
            model_name='session',
            name='limit_crossed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='session',
            name='session_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='session',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='children.child'),
        ),
        migrations.AlterField(
            model_name='session',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
