# Generated by Django 5.1.5 on 2025-05-04 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0004_remove_session_activity_remove_session_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='session',
            name='daily_progress',
            field=models.JSONField(blank=True, default=dict, help_text='Snapshot of progress at the end of the day'),
        ),
        migrations.AddField(
            model_name='session',
            name='game_sessions',
            field=models.JSONField(blank=True, default=list, help_text='List of game session IDs played on this day'),
        ),
        migrations.AddField(
            model_name='session',
            name='game_usage',
            field=models.JSONField(blank=True, default=dict, help_text='Time spent on each game type and performance metrics'),
        ),
        migrations.AlterField(
            model_name='session',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='session',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('child',), name='unique_active_session_per_child'),
        ),
    ]
